version: "3"
services:
  db:
    image: postgres:10.6-alpine
    restart: always
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=redmine
      - POSTGRES_PASSWORD=password
  redmine:
    image: redmine:4.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.data/redmine:/usr/src/redmine/files
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_USERNAME=redmine
      - REDMINE_DB_PASSWORD=password
